// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanskariVidhyalay.Model;

#nullable disable

namespace SanskariVidhyalay.Migrations.ContactDBMigrations
{
    [DbContext(typeof(ContactDB))]
    partial class ContactDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanskariVidhyalay.Models.Contact", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("Varchar(80)")
                        .HasColumnName("Email Address");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("Varchar(Max)")
                        .HasColumnName("Message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(30)")
                        .HasColumnName("Name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Subject");

                    b.HasKey("No");

                    b.ToTable("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
